import Bot from "../models/bot.model.js";
import User from "../models/user.model.js";

export const Message=async(req,res)=>{
   try {
    const {text}=req.body;
 
    if(!text?.trim()){
        return res.status(400).json({error:"Text cannot be empty"});
    }

    const user=await User.create({
        sender:"user",
        text
    })

    // Data
    const botResponses={
        "hi":"Hello i m good wbu",
  "hello": "Hi, How I can help you!!",
  "can we become friend": "Yes",
  "how are you": "I'm just a bot, but I'm doing great! How about you?",
  "what is your name?": "I’m ChatBot, your virtual assistant.",
  "who made you": "I was created by Harsh to help answer your questions.",
  "tell me a joke": "Why don’t skeletons fight each other? They don’t have the guts!",
  "what is the time": "I can’t see a clock, but your device should know.",
  "bye": "Goodbye! Have a great day.",
  "thank you": "You’re welcome!",
  "i love you": "That’s sweet! I’m here to help you anytime.",
  "where are you from": "I live in the cloud — no rent, no bills!",
  "what can you do": "I can chat with you, answer questions, and keep you company.",

 "what is python": "Python is a high-level, interpreted programming language known for simplicity and versatility.\n• Easy to read/write due to clean syntax (similar to English)\n• Dynamically typed and supports multiple paradigms (OOP, functional, procedural)\n• Extensive libraries for AI, data science, web, automation\n• Example: Used in Google, YouTube, Instagram, and machine learning applications",

"what is java?": "Java is a platform-independent, object-oriented programming language.\n• Famous for 'Write Once, Run Anywhere' due to JVM (Java Virtual Machine)\n• Used in enterprise systems, Android development, cloud apps\n• Provides features like garbage collection, strong memory management\n• Example: Banking systems, Android apps, large-scale enterprise applications",

"what is recursion": "Recursion is when a function calls itself to solve smaller parts of a problem.\n• Useful for problems that can be divided into subproblems (divide-and-conquer)\n• Requires a **base condition** to stop infinite looping\n• Commonly used in: factorial calculation, Fibonacci sequence, tree/graph traversal\n• Example in coding interview: 'Write a recursive function to reverse a linked list'",

"who is prime minister of india?": "Narendra Modi is the Prime Minister of India since May 2014.\n• Belongs to Bharatiya Janata Party (BJP)\n• Represents Varanasi constituency\n• Key initiatives: Digital India, Startup India, Swachh Bharat, Make in India\n• Interview Tip: Link to governance or technology (e.g., Digital India impact on IT industry)",

"what is g20": "The G20 (Group of Twenty) is an intergovernmental forum of 19 countries + the European Union.\n• Founded in 1999 to address global financial stability\n• Members include India, USA, China, Japan, EU, etc.\n• Discusses economic growth, climate change, sustainable development\n• Recent: India hosted G20 summit in 2023",

"tell me about yourself": "This is usually the first interview question.\nStructure:\n• Start with a brief intro (name, background, education/work)\n• Highlight your skills (technical + soft skills)\n• Share achievements (projects, internships, leadership roles)\n• Conclude with why you’re excited about this role\nExample: 'I am a Computer Science graduate skilled in Python and SQL. I completed an internship at XYZ where I optimized a database query, improving performance by 30%. I’m passionate about problem-solving and eager to contribute to your team’s success.'",

"why should we hire you": "HR wants to see your value-add.\n• Emphasize skills that match job requirements\n• Show enthusiasm and cultural fit\n• Example: 'I bring strong coding skills in Python and SQL, along with problem-solving ability proven through hackathons. I am also a quick learner and adapt well to team environments. I believe I can contribute to both technical delivery and innovative ideas.'",

"what is leadership": "Leadership is the ability to inspire and guide others toward achieving goals.\n• Key traits: vision, communication, accountability, decision-making\n• Example in interview: 'I led a college project team of 4, where I divided tasks, coordinated communication, and ensured deadlines. We successfully delivered a working prototype before schedule.'",

"who is virat kohli": "Virat Kohli is one of India’s greatest batsmen and former captain.\n• Known for consistency, fitness, and aggressive play\n• Holds record for fastest century in ODIs for India\n• Nicknamed 'Chase Master' for his performance in run-chases\n• Interview Tip: If asked about sports management, relate his discipline & fitness to leadership skills",

"what is ipl": "The Indian Premier League (IPL) is a professional T20 cricket league started in 2008.\n• Played annually in India, franchise-based teams\n• Combines cricket + entertainment (biggest sports league in India)\n• Significant for sports business, sponsorships, brand endorsements\n• Example: Chennai Super Kings (CSK) & Mumbai Indians (MI) are top teams",
"what is javascript": "JavaScript is a programming language used to build dynamic web pages.",
  "what is react": "React is a JavaScript library for building user interfaces.",
  "what is node js": "Node.js allows JavaScript to run on the server.",
  "what is express js": "Express.js is a Node.js framework for building backend APIs.",
  "what is mongodb": "MongoDB is a NoSQL database storing data in JSON-like documents.",
  "what is html": "HTML is the standard markup language for creating web pages.",
  "what is css": "CSS is used for styling and layout of web pages.",
  "what is api": "API stands for Application Programming Interface used for communication between software.",
  "what is json": "JSON is a lightweight data format used for data exchange.",
  "what is rest api": "REST API is a style of API architecture using HTTP methods.",
  
  "what is bootstrap": "Bootstrap is a CSS framework for building responsive websites.",
  "what is tailwind css": "Tailwind CSS is a utility-first CSS framework.",
  "what is git": "Git is a version control system used to track code changes.",
  "what is github": "GitHub is a hosting platform for Git repositories.",
  "what is hosting": "Hosting is a service that stores website files on a server.",
  "what is domain": "A domain is the address of a website on the internet.",
  "what is firebase": "Firebase is a cloud platform by Google offering backend services.",
  "what is jwt": "JWT is JSON Web Token used for authentication.",
  "what is authentication": "Authentication verifies a user's identity.",
  "what is authorization": "Authorization defines what an authenticated user can access.",

  "what is sql": "SQL is a language for managing relational databases.",
  "what is mysql": "MySQL is a popular relational database management system.",
  "what is postgresql": "PostgreSQL is an advanced open-source relational database.",
  "what is nosql": "NoSQL is a type of database that stores non-tabular data.",
  "what is docker": "Docker is a platform for containerizing applications.",
  "what is kubernetes": "Kubernetes manages and orchestrates containerized applications.",
  "what is cloud computing": "Cloud computing delivers services like storage and servers over the internet.",
  "what is aws": "AWS is Amazon Web Services, a cloud platform.",
  "what is azure": "Microsoft Azure is a cloud service provider.",
  "what is google cloud": "Google Cloud is Google's cloud service platform.",

  "what is oop": "OOP stands for Object-Oriented Programming.",
  "what is class in oop": "A class is a blueprint for creating objects.",
  "what is object in oop": "Object is an instance of a class.",
  "what is inheritance": "Inheritance allows one class to acquire properties of another.",
  "what is polymorphism": "Polymorphism allows methods to behave differently based on context.",
  "what is encapsulation": "Encapsulation hides internal data and exposes only necessary parts.",
  "what is abstraction": "Abstraction hides complex implementation details.",
  "what is compiler": "Compiler converts high-level code into machine code.",
  "what is interpreter": "Interpreter executes code line by line.",
  "what is algorithm": "An algorithm is a step-by-step method to solve a problem.",

  "what is data structure": "A data structure organizes data efficiently.",
  "what is array": "Array stores multiple values of same type in indexed form.",
  "what is linked list": "Linked list stores elements as nodes connected by pointers.",
  "what is stack": "Stack is LIFO data structure.",
  "what is queue": "Queue is FIFO data structure.",
  "what is tree": "Tree is a hierarchical data structure.",
  "what is binary tree": "Binary tree has max two children per node.",
  "what is graph": "Graph is a set of nodes connected by edges.",
  "what is hashmap": "Hashmap stores key-value pairs.",
  "what is sorting": "Sorting arranges data in a particular order.",

  "what is bubble sort": "Bubble sort compares and swaps adjacent elements.",
  "what is quick sort": "Quick sort uses divide and conquer technique.",
  "what is merge sort": "Merge sort splits arrays and merges them in order.",
  "what is searching": "Searching finds an element in a collection.",
  "what is linear search": "Linear search checks elements one by one.",
  "what is binary search": "Binary search works on sorted arrays and splits search range.",
  "what is dns": "DNS translates domain names into IP addresses.",
  "what is ip address": "IP address identifies a device on the internet.",
  "what is http": "HTTP is a protocol for transferring web content.",
  "what is https": "HTTPS is secure version of HTTP.",

  "what is ssl": "SSL is a security technology that encrypts data.",
  "what is tcp": "TCP is a connection-oriented communication protocol.",
  "what is udp": "UDP is a faster but connectionless protocol.",
  "what is os": "Operating system manages hardware and software resources.",
  "what is linux": "Linux is an open-source operating system.",
  "what is unix": "Unix is a multiuser operating system.",
  "what is windows": "Windows is an operating system developed by Microsoft.",
  "what is android": "Android is a mobile operating system by Google.",
  "what is ios": "iOS is Apple's mobile operating system.",
  "what is api key": "API key is a token to authenticate API requests.",

  "what is chatbot": "A chatbot is a software that answers questions automatically.",
  "what is machine learning": "Machine learning enables computers to learn from data.",
  "what is ai": "AI is simulation of human intelligence by machines.",
  "what is neural network": "Neural networks are algorithms inspired by the brain.",
  "what is deep learning": "Deep learning uses layered neural networks.",
  "what is dataset": "Dataset is a collection of data used for training.",
  "what is model": "A model is a learned pattern from data.",
  "what is training in ml": "Training teaches a model from data.",
  "what is testing in ml": "Testing evaluates a trained model.",
  "what is prediction": "Prediction is the output given by an ML model.",

  "what is ui": "UI stands for User Interface.",
  "what is ux": "UX stands for User Experience.",
  "what is wireframe": "Wireframe is a basic layout of an app or site.",
  "what is prototype": "Prototype is an early model of a product.",
  "what is figma": "Figma is a tool for UI/UX design.",
  "what is canva": "Canva is a graphic designing platform.",
  "what is seo": "SEO is optimizing websites to rank on search engines.",
  "what is sem": "SEM is paid advertising on search engines.",
  "what is digital marketing": "Digital marketing promotes brands online.",
  "what is influencer marketing": "Influencer marketing uses influencers for promotion.",

  "what is cpu": "CPU is the brain of the computer.",
  "what is ram": "RAM is temporary memory used for processing.",
  "what is rom": "ROM stores permanent data.",
  "what is hard disk": "Hard disk is long-term storage.",
  "what is ssd": "SSD is a faster version of storage compared to HDD.",
  "what is gpu": "GPU handles graphics and parallel processing.",
  "what is motherboard": "Motherboard connects all hardware components.",
  "what is power supply": "Power supply provides electrical power to components.",
  "what is network": "A network is a collection of devices connected together.",
  "what is router": "Router connects networks and directs traffic.",

  "what is modem": "Modem connects your network to the internet.",
  "what is hotspot": "Hotspot shares internet wirelessly.",
  "what is bluetooth": "Bluetooth is wireless communication for short distances.",
  "what is wifi": "WiFi provides wireless internet connectivity.",
  "what is encryption": "Encryption converts data into secure code.",
  "what is firewall": "Firewall protects networks from unauthorized access.",
  "what is virus": "A virus is malicious software that infects systems.",
  "what is malware": "Malware is harmful software created to damage systems.",
  "what is trojan": "A trojan disguises itself as legitimate software.",
  "what is ransomware": "Ransomware locks data and demands payment.",

  "what is backlink": "Backlink is a link from one website to another.",
  "what is hosting server": "Hosting server stores website files.",
  "what is cpanel": "cPanel is a control panel for hosting management.",
  "what is ftp": "FTP transfers files between computer and server.",
  "what is lighthouse": "Lighthouse analyzes website performance.",
  "what is webpack": "Webpack bundles JavaScript modules.",
  "what is vite": "Vite is a fast frontend build tool.",
  "what is babel": "Babel converts modern JavaScript into older versions.",
  "what is typescript": "TypeScript is JavaScript with type support.",
  "what is npm": "NPM is a package manager for JavaScript.",

  "what is yarn": "Yarn is another package manager for JavaScript.",
  "what is redux": "Redux is a state management library.",
  "what is context api": "Context API provides global state in React.",
  "what is useState": "useState is a React hook for storing state.",
  "what is useEffect": "useEffect runs side effects in React.",
  "what is promise": "Promise represents an asynchronous operation.",
  "what is async await": "Async await simplifies asynchronous programming.",
  "what is callback": "Callback is a function passed to another function.",
  "what is event loop": "Event loop manages asynchronous operations in JS.",
  "what is hoisting": "Hoisting moves declarations to the top in JavaScript.",

  "what is closure": "Closure gives access to parent scope even after function finishes.",
  "what is dom": "DOM is a programming interface for HTML documents.",
  "what is bom": "BOM is Browser Object Model.",
  "what is localhost": "Localhost represents your local computer server.",
  "what is port": "Port is a communication endpoint in networking.",
  "what is middleware": "Middleware processes requests before they reach the route.",
  "what is router in express": "Router organizes API routes.",
  "what is schema in mongodb": "Schema defines structure of documents.",
  "what is collection in mongodb": "Collection stores multiple documents.",
  "what is document in mongodb": "Document is a single record in MongoDB.",

  "what is load balancing": "Load balancing distributes work across servers.",
  "what is api testing": "API testing ensures APIs work correctly.",
  "what is unit testing": "Unit testing checks individual components.",
  "what is integration testing": "Integration testing checks combined components.",
  "what is deployment": "Deployment publishes your application to production.",
  "what is production": "Production is the live environment for users.",
  "what is staging": "Staging is pre-production environment for testing.",
  "what is debugging": "Debugging means fixing errors in code.",
  "what is framework": "Framework provides predefined structure for development.",
  "what is library": "Library provides reusable functions for developers.",
  "who is the prime minister of india": "Narendra Modi is the Prime Minister of India.",
  "who is the president of the usa": "Joe Biden is the President of the United States.",
  "who is the president of russia": "Vladimir Putin is the President of Russia.",
  "who is the prime minister of uk": "Rishi Sunak is the Prime Minister of the United Kingdom.",
  "who is the president of france": "Emmanuel Macron is the President of France.",
  "who is the president of china": "Xi Jinping is the President of China.",
  "who is the prime minister of japan": "Fumio Kishida is the Prime Minister of Japan.",
  "who is the founder of microsoft": "Bill Gates is the founder of Microsoft.",
  "who is the founder of apple": "Steve Jobs is the founder of Apple.",
  "who is the founder of facebook": "Mark Zuckerberg is the founder of Facebook.",

  "who is the richest man in the world": "Elon Musk is considered one of the richest men in the world.",
  "who is the ceo of tesla": "Elon Musk is the CEO of Tesla.",
  "who is the ceo of google": "Sundar Pichai is the CEO of Google.",
  "who is the ceo of amazon": "Andy Jassy is the CEO of Amazon.",
  "who is the ceo of apple": "Tim Cook is the CEO of Apple.",
  "who is the ceo of meta": "Mark Zuckerberg is the CEO of Meta.",
  "who is the founder of spacex": "Elon Musk is the founder of SpaceX.",
  "who is the founder of alibaba": "Jack Ma is the founder of Alibaba.",
  "who is the founder of relianc e": "Dhirubhai Ambani founded Reliance.",
  "who is mukesh ambani": "Mukesh Ambani is an Indian billionaire and chairman of Reliance Industries.",

  "who is gautam adani": "Gautam Adani is an Indian industrialist and chairman of the Adani Group.",
  "who is virat kohli": "Virat Kohli is an Indian cricketer and former captain of the Indian team.",
  "who is ms dhoni": "MS Dhoni is a former Indian cricket captain and World Cup winner.",
  "who is sachin tendulkar": "Sachin Tendulkar is a legendary Indian cricketer known as the God of Cricket.",
  "who is rohit sharma": "Rohit Sharma is the captain of the Indian cricket team.",
  "who is lionel messi": "Lionel Messi is an Argentine footballer considered one of the best in the world.",
  "who is cristiano ronaldo": "Cristiano Ronaldo is a Portuguese football superstar.",
  "who is neymar": "Neymar is a Brazilian professional footballer.",
  "who is pele": "Pele was a famous Brazilian football legend.",
  "who is diego maradona": "Maradona was an Argentine football legend.",

  "who is elon musk": "Elon Musk is an entrepreneur who founded Tesla, SpaceX, and other companies.",
  "who is bill gates": "Bill Gates is the co-founder of Microsoft and a philanthropist.",
  "who is steve jobs": "Steve Jobs was the co-founder of Apple.",
  "who is warren buffett": "Warren Buffett is a famous American investor.",
  "who is jeff bezos": "Jeff Bezos is the founder of Amazon.",
  "who is jack ma": "Jack Ma is a Chinese entrepreneur and founder of Alibaba.",
  "who is mark zuckerberg": "Mark Zuckerberg is the founder of Facebook.",
  "who is sundar pichai": "Sundar Pichai is the CEO of Google and Alphabet.",
  "who is satya nadella": "Satya Nadella is the CEO of Microsoft.",
  "who is tim cook": "Tim Cook is the CEO of Apple.",

  "what is the capital of india": "New Delhi is the capital of India.",
  "what is the capital of usa": "Washington, D.C. is the capital of the United States.",
  "what is the capital of china": "Beijing is the capital of China.",
  "what is the capital of japan": "Tokyo is the capital of Japan.",
  "what is the capital of russia": "Moscow is the capital of Russia.",
  "what is the capital of france": "Paris is the capital of France.",
  "what is the capital of uk": "London is the capital of the United Kingdom.",
  "what is the capital of germany": "Berlin is the capital of Germany.",
  "what is the capital of canada": "Ottawa is the capital of Canada.",
  "what is the capital of australia": "Canberra is the capital of Australia.",

  "what is the capital of italy": "Rome is the capital of Italy.",
  "what is the capital of spain": "Madrid is the capital of Spain.",
  "what is the capital of brazil": "Brasilia is the capital of Brazil.",
  "what is the capital of argentina": "Buenos Aires is the capital of Argentina.",
  "what is the capital of nepal": "Kathmandu is the capital of Nepal.",
  "what is the capital of sri lanka": "Colombo is the commercial capital and Sri Jayawardenepura Kotte is the official capital.",
  "what is the capital of pakistan": "Islamabad is the capital of Pakistan.",
  "what is the capital of bangladesh": "Dhaka is the capital of Bangladesh.",
  "what is the capital of south korea": "Seoul is the capital of South Korea.",
  "what is the capital of north korea": "Pyongyang is the capital of North Korea.",

  "which is the largest country in the world": "Russia is the largest country in the world.",
  "which is the smallest country in the world": "Vatican City is the smallest country in the world.",
  "which is the largest ocean": "The Pacific Ocean is the largest ocean.",
  "which is the tallest mountain": "Mount Everest is the tallest mountain in the world.",
  "which is the longest river": "The Nile River is considered the longest river.",
  "which is the largest desert": "The Sahara Desert is the largest hot desert.",
  "which is the largest continent": "Asia is the largest continent.",
  "which is the smallest continent": "Australia is the smallest continent.",
  "which is the largest animal": "The blue whale is the largest animal on Earth.",
  "which is the largest bird": "The ostrich is the largest bird.",

  "who wrote the ramayana": "Valmiki wrote the original Ramayana.",
  "who wrote the mahabharata": "Vyasa wrote the Mahabharata.",
  "who is lord rama": "Lord Rama is a major deity in Hinduism and the hero of Ramayana.",
  "who is lord krishna": "Lord Krishna is a Hindu deity and the speaker of Bhagavad Gita.",
  "who is buddha": "Gautam Buddha was the founder of Buddhism.",
  "who is guru nanak": "Guru Nanak was the founder of Sikhism.",
  "who is swami vivekananda": "Swami Vivekananda was an Indian monk and spiritual leader.",
  "who is mahatma gandhi": "Mahatma Gandhi was the leader of India's freedom movement.",
  "who is jawaharlal nehru": "Jawaharlal Nehru was the first Prime Minister of India.",
  "who is dr ambedkar": "Dr. B. R. Ambedkar drafted the Indian Constitution.",

  "who is sardar patel": "Sardar Patel unified India’s princely states.",
  "who is bhagat singh": "Bhagat Singh was an Indian freedom fighter.",
  "who is subhash chandra bose": "Subhash Chandra Bose was an Indian nationalist leader.",
  "who is apj abdul kalam": "APJ Abdul Kalam was the 11th President of India and a scientist.",
  "who is kalpana chawla": "Kalpana Chawla was the first Indian woman in space.",
  "who is neha kakkar": "Neha Kakkar is a popular Indian singer.",
  "who is arijit singh": "Arijit Singh is a famous Indian playback singer.",
  "who is alia bhatt": "Alia Bhatt is a popular Bollywood actress.",
  "who is salman khan": "Salman Khan is a famous Bollywood actor.",
  "who is shah rukh khan": "Shah Rukh Khan is a legendary Bollywood actor.",

  "who is amitabh bachchan": "Amitabh Bachchan is a legendary Indian film actor.",
  "who is akshay kumar": "Akshay Kumar is a well-known Bollywood actor.",
  "who is rajinikanth": "Rajinikanth is a legendary South Indian actor.",
  "who is kamal haasan": "Kamal Haasan is a famous Indian actor and director.",
  "who is ranbir kapoor": "Ranbir Kapoor is a popular Indian actor.",
  "who is deepika padukone": "Deepika Padukone is a leading Bollywood actress.",
  "who is priyanka chopra": "Priyanka Chopra is a global Indian actress and singer.",
  "who is taylor swift": "Taylor Swift is an American singer and songwriter.",
  "who is selena gomez": "Selena Gomez is an American singer and actress.",
  "who is justin bieber": "Justin Bieber is a Canadian singer.",

  "who is beyonce": "Beyoncé is an American singer and performer.",
  "who is rihanna": "Rihanna is a Barbadian singer and entrepreneur.",
  "who is drake": "Drake is a Canadian rapper and singer.",
  "who is eminem": "Eminem is an American rapper considered one of the greatest.",
  "who is michael jackson": "Michael Jackson was the King of Pop.",
  "who is elvis presley": "Elvis Presley was the King of Rock and Roll.",
  "who is lebron james": "LeBron James is an American basketball superstar.",
  "who is kobe bryant": "Kobe Bryant was a legendary basketball player.",
  "who is michael jordan": "Michael Jordan is considered one of the greatest basketball players.",
  "who is usain bolt": "Usain Bolt is a Jamaican sprinter known as the fastest man alive.",

  "which country has the highest population": "China has the highest population, followed by India.",
  "which country has the largest economy": "The United States has the largest economy.",
  "which country is called the land of rising sun": "Japan is called the Land of the Rising Sun.",
  "which country is called the land of midnight sun": "Norway is called the Land of the Midnight Sun.",
  "which country is called the land of kangaroos": "Australia is called the Land of Kangaroos.",
  "which country is called the land of pyramids": "Egypt is known as the Land of Pyramids.",
  "which country has taj mahal": "India is home to the Taj Mahal.",
  "which country invented pizza": "Italy invented pizza.",
  "which country invented tea": "China is believed to have invented tea.",
  "which country invented football": "England invented modern football.",

  "who discovered gravity": "Sir Isaac Newton discovered gravity.",
  "who proposed theory of relativity": "Albert Einstein proposed the theory of relativity.",
  "who discovered electricity": "Benjamin Franklin is often credited with discovering electricity.",
  "who invented light bulb": "Thomas Edison invented the practical light bulb.",
  "who invented telephone": "Alexander Graham Bell invented the telephone.",
  "who invented aeroplane": "The Wright Brothers invented the airplane.",
  "who invented computer": "Charles Babbage is known as the father of the computer.",
  "who invented internet": "The internet was invented by scientists at ARPANET.",
  "who invented tv": "John Logie Baird invented the television.",
  "who invented radio": "Guglielmo Marconi invented the radio."


}

const normalizedText = text.toLowerCase().trim();

const botResponse = botResponses[normalizedText] || "Sorry, I don't understand that!!!";

const bot = await Bot.create({
    text: botResponse
})

return res.status(200).json({
    userMessage:user.text,
    botMessage:bot.text,
})
   } catch (error) {
    console.log("Error in Message Controller:", error);
    return res.status(500).json({error:"Internal Server Error"});
   }
}